//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_MARKET_PRICE_L_Province
    {
        public int MPL_ID { get; set; }
        public Nullable<System.DateTime> DATE_SV { get; set; }
        public Nullable<decimal> LAND_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<decimal> REG_MI_CONSTR { get; set; }
        public Nullable<decimal> REG_AMT { get; set; }
        public Nullable<decimal> REG_P_WAH { get; set; }
        public Nullable<decimal> RVAL_P_WAH { get; set; }
        public Nullable<decimal> RVAL_AMT { get; set; }
        public Nullable<decimal> RUSE_FLAG { get; set; }
        public Nullable<decimal> RS_VAL_P_WAH { get; set; }
        public Nullable<decimal> QREG_MI_CONSTR { get; set; }
        public Nullable<decimal> QREG_AMT { get; set; }
        public Nullable<decimal> QREG_P_WAH { get; set; }
        public Nullable<decimal> QUSE_FLAG { get; set; }
        public Nullable<decimal> QS_VAL_P_WAH { get; set; }
        public Nullable<decimal> OREG_MI_CONSTR { get; set; }
        public Nullable<decimal> OREG_AMT { get; set; }
        public Nullable<decimal> OREG_P_WAH { get; set; }
        public Nullable<decimal> QODDS { get; set; }
        public Nullable<decimal> OUSE_FLAG { get; set; }
        public Nullable<decimal> OS_VAL_P_WAH { get; set; }
        public string OINFORMATION { get; set; }
        public Nullable<decimal> LREG_MI_CONSTR { get; set; }
        public Nullable<decimal> LREG_AMT { get; set; }
        public Nullable<decimal> LREG_P_WAH { get; set; }
        public Nullable<decimal> LLEASE_P_MONTH { get; set; }
        public Nullable<decimal> LEXPENSE { get; set; }
        public Nullable<decimal> YIELD { get; set; }
        public Nullable<decimal> LUSE_FLAG { get; set; }
        public Nullable<decimal> LS_VAL_P_WAH { get; set; }
        public string LINFORMATION { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> USE_FLAG { get; set; }
        public string CHANGWAT_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string AMPHUR_CODE { get; set; }
        public string TUMBON_CODE { get; set; }
        public string UTM_CODE { get; set; }
        public Nullable<decimal> UTM_NO_P { get; set; }
        public string UTM_NO { get; set; }
        public string UTM_PAGE { get; set; }
        public string UTM_RATIO { get; set; }
        public Nullable<decimal> UTM_LANDNO { get; set; }
        public Nullable<decimal> CHANODE_NO { get; set; }
        public Nullable<decimal> SURVEY_NO { get; set; }
        public Nullable<decimal> NS3A_NO { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public string REG_CODE { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<int> NRAI { get; set; }
        public Nullable<int> NNHAN { get; set; }
        public Nullable<int> NWAH { get; set; }
        public Nullable<decimal> DREMAIN { get; set; }
        public Nullable<int> NUM_REG { get; set; }
        public string CONSTR_FLAG { get; set; }
        public Nullable<decimal> AS_RATIO { get; set; }
        public Nullable<decimal> CONSTR_AMT { get; set; }
        public string CONSTR_CODE_ALL { get; set; }
        public string CONSTR_YEAR_ALL { get; set; }
        public string CONSTR_AREA_ALL { get; set; }
        public Nullable<int> RP1_ORDER_ID { get; set; }
        public Nullable<int> PARCEL_RN { get; set; }
        public Nullable<int> NS3K_RN { get; set; }
        public string MAPZONE { get; set; }
    }
}
