
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TDM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PROV_IMPACT1
{

    public int ID { get; set; }

    public int PROJECT_ID { get; set; }

    public string PROV_CODE { get; set; }

}

}
