//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MAS_AMPHUR
    {
        public decimal AMPHUR_SEQ { get; set; }
        public string AMPHUR_ID { get; set; }
        public string AMPHUR_NAME_TH { get; set; }
        public string AMPHUR_NAME_EN { get; set; }
        public Nullable<decimal> PROVINCE_SEQ { get; set; }
    }
}
