//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDASSETEntities : DbContext
    {
        public TDASSETEntities()
            : base("name=TDASSETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POI> POIs { get; set; }
        public virtual DbSet<PROVINCE> PROVINCEs { get; set; }
        public virtual DbSet<PROJECT_AREA_47> PROJECT_AREA_47 { get; set; }
        public virtual DbSet<PROJECT_AREA_48> PROJECT_AREA_48 { get; set; }
        public virtual DbSet<AMPHOE> AMPHOEs { get; set; }
        public virtual DbSet<TAMBOL> TAMBOLs { get; set; }
        public virtual DbSet<PROJECT_PARCEL_47> PROJECT_PARCEL_47 { get; set; }
        public virtual DbSet<PROJECT_PARCEL_48> PROJECT_PARCEL_48 { get; set; }
        public virtual DbSet<PARCEL_47_10> PARCEL_47_10 { get; set; }
    }
}
